#include "stm32g070xx.h"


void    Parameter_Init(void);
void    Parameter_Get_Disp_Comm_Val(void);
int16_t GET_ICE_MAKER_VALVE_ON_TIME(void);
int16_t GET_ICE_MAKER_VALVE_OFF_TIME(void);
int16_t GET_ICE_MAKER_VALVE_ON_CYCLE(void);
int32_t GET_ICE_MAKER_AFTER_VALVE_TIME(void);
int32_t GET_ICE_MAKER_IC_FULL_WAIT_TIME(void);
int     GET_ICE_MAKER_SET_ICE_TEMP(void);
int32_t GET_ICE_MAKER_HEATER_TEMP_RANGE(void);
int32_t GET_ICE_MAKER_HEATER_RUNNING_TEMP_MIN(void);
int32_t GET_ICE_MAKER_HEATER_RUNNING_TEMP_MAX(void);
int16_t GET_ICE_MAKER_HEATER_RUN_TIME(void);
int8_t  GET_WATER_DISPENSER_MID_WATER_FILL_TIME_SEC(void);
int8_t  GET_WATER_DISPENSER_LOW_WATER_FILL_TIME_SEC(void);