/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.40.0.0
 *
 * Project: 'Ice_maker_ice_crasher_and_water_disp_code_rearrv_646L' 
 * Target:  'Target 1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32g0xx.h"

/* Keil::Device:Startup@1.4.2 */
#define RTE_DEVICE_STARTUP_STM32G0XX    /* Device Startup for STM32G0 */


#endif /* RTE_COMPONENTS_H */
